#!/bin/bash

# backlight device here:
device="amdgpu_bl0"

# current brightness
current="`cat /sys/class/backlight/$device/brightness`"
# max brightness
max="`cat /sys/class/backlight/$device/max_brightness`"

# no value: print current
if [ -z "$1" ]; then
	echo $current
	exit
fi

val="$1"
# start with + add value
if [[ ${val::1} == "+" ]]; then
	val=$(($current + $val))
fi
# start with - sub value
if [[ ${val::1} == "-" ]]; then
	val=$(($current + $val))	# val is negative
fi

#if val over max, set to max
[[ $val -gt $max ]] && val="$max"
#if val below 0, set to 0
[[ $val -lt 0 ]] && val=0

[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"	# as sudo
# echo val to device
echo $val > /sys/class/backlight/$device/brightness
